### ISSUE TITLE
bug: pgen & bed readers fail due to `row_nr()`

### ISSUE THREAD

**Issue by kscott-1** [AI-sandbox/snputils#7]
Error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/snputils/snp/io/read/functional.py", line 46, in read_pgen
    return PGENReader(filename).read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/snputils/snp/io/read/pgen.py", line 107, in read
    variant_idxs = pvar.filter(pl.col("ID").is_in(variant_ids)).row_nr().to_numpy()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'row_nr'

**Comment by salcc** [comment]
Thanks for the report and fix! v0.2.9 includes the fix.

**Comment by traben** [comment]
Nice package!

I think this bug still exists in the 

> snputils/snp/io/read/bed.py

File for bed reading. Explicitly the issue is that the `row_nr` was deprecated since polars version 0.20.4 and is now replaced with `index`
